@baseUrl = http://localhost:7000

GET {{baseUrl}}/

###
GET {{baseUrl}}/container
Content-Type: application/json

{
    "containerId": "debf309ddd46c9dc6b56c2a353be971835f0c8708fe9648a13c4cdea0c7980cb",
    "containerPort": "32768"
}