@baseUrl = http://127.0.0.1:5000
@containerId = empty

GET {{baseUrl}}/

###
POST {{baseUrl}}/container
Accept: application/json
Content-Type: application/json

{
    "docker_container_id": "{{containerId}}"
}