@baseUrl = http://127.0.0.1:5000
@containerId = 636eaf45d5496a9c6ef84d778bb61a00e036778a4389c1f588906aef5d01c17d

GET {{baseUrl}}/

###
POST {{baseUrl}}/container
Accept: application/json
Content-Type: application/json

{
    "docker_container_id": "{{containerId}}"
}