@baseUrl = http://127.0.0.1:5000
@containerId = 68daed9a9ecd460e13494c97d901fefdf7afcca868478a0900f1650275d4b67c

GET {{baseUrl}}/

###
GET {{baseUrl}}/container
Accept: application/json
Content-Type: application/json
Cookie: docker_container_id={{containerId}}
